
#ifndef GNNPLUGINSHARED_GLOBAL_H
#define GNNPLUGINSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GNNPLUGIN_LIBRARY)
#define GNNPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define GNNPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GNNPLUGINSHARED_GLOBAL_H
