#ifndef PLUGINNODEINTERFACE_GLOBAL_H
#define PLUGINNODEINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGINNODEINTERFACE_LIBRARY)
#define PLUGINNODEINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#define PLUGINNODEINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGININTERFACE_GLOBAL_H
