
#ifndef TRACERUPDATERECEIVERPLUGINSHARED_GLOBAL_H
#define TRACERUPDATERECEIVERPLUGINSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRACERUPDATERECEIVERPLUGIN_LIBRARY)
#define TRACERUPDATERECEIVERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define TRACERUPDATERECEIVERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TRACERUPDATERECEIVERPLUGIN_GLOBAL_H
