#ifndef ASSIMPLOADERPLUGIN_GLOBAL_H
#define ASSIMPLOADERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ASSIMPLOADERPLUGIN_LIBRARY)
#define ASSIMPLOADERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define ASSIMPLOADERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EXAMPLEPLUGIN_GLOBAL_H
