
#ifndef BASICONNXPLUGINSHARED_GLOBAL_H
#define BASICONNXPLUGINSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASICONNXPLUGIN_LIBRARY)
#define BASICONNXPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define BASICONNXPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASICONNXPLUGINSHARED_GLOBAL_H
