
#ifndef DATAEXPORTPLUGINSHARED_GLOBAL_H
#define DATAEXPORTPLUGINSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATAEXPORTPLUGIN_LIBRARY)
#define DATAEXPORTPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define DATAEXPORTPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATAEXPORTPLUGINSHARED_GLOBAL_H
