#ifndef PLUGININTERFACE_GLOBAL_H
#define PLUGININTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGININTERFACE_LIBRARY)
#define PLUGININTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#define PLUGININTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGININTERFACE_GLOBAL_H
