#ifndef ANIMHOSTCORESHARED_GLOBAL_H
#define ANIMHOSTCORESHARED_GLOBAL_H


#include <QtCore/QtGlobal>

#define NODE_EDITOR_SHARED 1

#if defined(ANIMHOSTCORE_LIBRARY)
#define ANIMHOSTCORESHARED_EXPORT Q_DECL_EXPORT
#else
#define ANIMHOSTCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ANIMHOSTCORESHARED_GLOBAL_H