
#ifndef MODEADAPTIVEPREPROCESSPLUGINSHARED_GLOBAL_H
#define MODEADAPTIVEPREPROCESSPLUGINSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODEADAPTIVEPREPROCESSPLUGIN_LIBRARY)
#define MODEADAPTIVEPREPROCESSPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define MODEADAPTIVEPREPROCESSPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODEADAPTIVEPREPROCESSPLUGINSHARED_GLOBAL_H
