
#ifndef JOINTVELOCITYPLUGINSHARED_GLOBAL_H
#define JOINTVELOCITYPLUGINSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(JOINTVELOCITYPLUGIN_LIBRARY)
#define JOINTVELOCITYPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define JOINTVELOCITYPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // JOINTVELOCITYPLUGIN_GLOBAL_H
