#ifndef JOINTPOSITIONPLUGIN_GLOBAL_H
#define JOINTPOSITIONPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(JOINTPOSITIONPLUGIN_LIBRARY)
#define JOINTPOSITIONPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define JOINTPOSITIONPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // JOINTPOSITIONPLUGIN_GLOBAL_H
