
#ifndef HISTORYPLUGINSHARED_GLOBAL_H
#define HISTORYPLUGINSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HISTORYPLUGIN_LIBRARY)
#define HISTORYPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define HISTORYPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HISTORYPLUGINSHARED_GLOBAL_H
