
#ifndef RUNTRIGGERPLUGINSHARED_GLOBAL_H
#define RUNTRIGGERPLUGINSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RUNTRIGGERPLUGIN_LIBRARY)
#define RUNTRIGGERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define RUNTRIGGERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RUNTRIGGERPLUGINSHARED_GLOBAL_H
