#ifndef TRACERPLUGINSHARED_GLOBAL_H
#define TRACERPLUGINSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRACERPLUGIN_LIBRARY)
#define TRACERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define TRACERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TRACERPLUGINSHARED_GLOBAL_H