
#ifndef ANIMATIONFRAMESELECTORPLUGINSHARED_GLOBAL_H
#define ANIMATIONFRAMESELECTORPLUGINSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ANIMATIONFRAMESELECTORPLUGIN_LIBRARY)
#define ANIMATIONFRAMESELECTORPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define ANIMATIONFRAMESELECTORPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ANIMATIONFRAMESELECTORPLUGINSHARED_GLOBAL_H
