
#ifndef TRACERSCENERECEIVERPLUGINSHARED_GLOBAL_H
#define TRACERSCENERECEIVERPLUGINSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRACERSCENERECEIVERPLUGIN_LIBRARY)
#define TRACERSCENERECEIVERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define TRACERSCENERECEIVERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TRACERSCENERECEIVERPLUGINSHARED_GLOBAL_H
