#ifndef TESTDATASOURCEPLUGINSHARED_GLOBAL_H
#define TESTDATASOURCEPLUGINSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TESTDATASOURCEPLUGIN_LIBRARY)
#define TESTDATASOURCEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define TESTDATASOURCEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EXAMPLEPLUGIN_GLOBAL_H
