
#ifndef CHARACTERSELECTORPLUGINSHARED_GLOBAL_H
#define CHARACTERSELECTORPLUGINSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHARACTERSELECTORPLUGIN_LIBRARY)
#define CHARACTERSELECTORPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define CHARACTERSELECTORPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CHARACTERSELECTORPLUGINSHARED_GLOBAL_H
