#ifndef EXAMPLEPLUGIN_GLOBAL_H
#define EXAMPLEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EXAMPLEPLUGIN_LIBRARY)
#define EXAMPLEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define EXAMPLEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EXAMPLEPLUGIN_GLOBAL_H
