#ifndef DEEPLOCOMOTIONPLUGINSHARED_GLOBAL_H
#define DEEPLOCOMOTIONPLUGINSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DEEPLOCOMOTIONPLUGIN_LIBRARY)
#define DEEPLOCOMOTIONPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define DEEPLOCOMOTIONPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DEEPLOCOMOTIONPLUGINSHARED_GLOBAL_H