
#ifndef COORDINATECONVERTERPLUGINSHARED_GLOBAL_H
#define COORDINATECONVERTERPLUGINSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COORDINATECONVERTERPLUGIN_LIBRARY)
#define COORDINATECONVERTERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define COORDINATECONVERTERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COORDINATECONVERTERPLUGINSHARED_GLOBAL_H
