
#ifndef TRACERUPDATESENDERPLUGINSHARED_GLOBAL_H
#define TRACERUPDATESENDERPLUGINSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRACERUPDATESENDERPLUGIN_LIBRARY)
#define TRACERUPDATESENDERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define TRACERUPDATESENDERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TRACERUPDATESENDERPLUGINSHARED_GLOBAL_H
